# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FZHk5pU3iKb_s5IE1_SnE7f7JNccd6IA
"""

import random

l = []
while len(l) < 90:
    numero = random.randint(1,90)
    if numero not in l:
        l.append(numero)
    print("il numero estratto è",numero,l)